import { useState, useEffect, useRef, type FormEvent, type ReactNode } from "react";

const NAV_LINKS = ["Home", "Projects", "Experience", "Skills", "Contact"];

const PROJECTS = [
  {
    id: "01",
    title: "Yeast Life Support Rocket Payload",
    category: "Aerospace",
    org: "Space Technologies and Rocketry",
    tags: ["SolidWorks", "Python", "Fluid Systems"],
    description:
      "Designed a life support payload providing proof-of-concept for organ viability in deep space. System diffuses CO₂ out of fluid during rocket travel and sustains yeast metabolism. Components include a peristaltic pump (cardiovascular), PDMS gas exchanger (pulmonary), and thermos reaction chamber (respiration).",
    specs: { membrane: "100μm PDMS", pump: "Peristaltic", method: "SLA print" },
    details: [
      { heading: "Problem", text: "An organ transported for transplant must remain viable. This payload explored a proof of concept for sustaining life-support conditions during deep-space travel." },
      { heading: "System architecture", text: "The system is organized around three biological analogues: a peristaltic pump acts as the heart, silicon tubing as arteries, and a PDMS gas exchanger as the pulmonary component. A thermos reaction chamber provides insulated respiration storage." },
      { heading: "Diffusion system", text: "A semi-permeable 100 μm PDMS membrane allows CO₂ to diffuse from the fluid. An SLA-printed mesh bracket supports the membrane and provides area for gas diffusion, secured with M2 and M3 screws and inserts." },
      { heading: "Integration and testing", text: "The payload slots into the bulkhead with vertical locating pins and a removable annulus. Fluid testing used a pipe, peristaltic pump, and power supply, with measured behavior compared against theoretical power and fluid-flow calculations." },
    ],
    image: "/yeast-payload.png",
    year: "2024–2026",
  },
  {
    id: "02",
    title: "Wind Turbine",
    category: "Energy",
    org: "3D Design Project",
    tags: ["SolidWorks FEA", "Topology Opt.", "GD&T"],
    description:
      "Radially symmetric wind tower designed to resist aerodynamic forces from all directions. Low angle of attack, 3-blade airfoil design for stable lift. Von Mises FEA stress analysis and topology optimization yielded a structure optimized for minimal deflection. Achieved 12.8% efficiency vs. 15.6 W available wind power.",
    specs: { efficiency: "12.8%", analysis: "Von Mises", blades: "3-blade" },
    details: [
      { heading: "Design goal", text: "Maximize power generated by the blade design while demonstrating reliable wind-energy generation. The radially symmetric tower resists aerodynamic forces from all directions." },
      { heading: "Analysis", text: "A low-angle-of-attack, three-blade airfoil creates stable lift. Von Mises FEA stress analysis and topology optimization produced an optimized structure designed for minimal deflection." },
      { heading: "Deflection test", text: "A rubber stopper, digital indicator, and pulley were used to create a repeatable deflection test. Results were compared with the theoretical FEA simulation to validate structural integrity." },
      { heading: "Power test", text: "A digital tachometer, reflective tape, and wind machine measured actual performance. With 15.6 W of available wind power and 2 W measured output, the turbine achieved 12.8% efficiency." },
    ],
    image: "/wind-turbine.png",
    year: "2024",
  },
  {
    id: "03",
    title: "Automatic Dog Pill Dispenser",
    category: "Mechatronics",
    org: "Product Design Project",
    tags: ["Onshape", "Arduino", "C++"],
    description:
      "Automated pill dispenser that evenly coats flavor around a dog pill to aid medication compliance. Prototype automatically coats 1.37 mL average dog pill using a lead screw, motor, and syringe. Included hand calculations for fluid flow, power transmission, and electrical component specification.",
    specs: { dose: "1.37 mL", actuation: "Lead screw", UI: "LCD + buttons" },
    details: [
      { heading: "Problem", text: "Dogs often refuse medication because of taste or past experiences, while manually flavoring a pill is tedious and inconsistent." },
      { heading: "User flow", text: "The user inserts a pill into the dispensing case and places soft food, such as peanut butter, into the syringe. The automated mechanism then coats the pill evenly." },
      { heading: "Prototype engineering", text: "The prototype coats an average 1.37 mL dog pill using a lead screw, motor, and syringe. Design decisions balanced software, hardware, and customer requirements." },
      { heading: "Technical work", text: "The project included hand calculations for fluid flow, power transmission, and electrical components, along with hardware specification and routing." },
    ],
    image: "/dog-pill-dispenser.png",
    year: "2024",
  },
  {
    id: "04",
    title: "IoT Drumstick Tutor",
    category: "Electronics",
    org: "Electronic Design Project",
    tags: ["ESP-32", "Python", "PID Control"],
    description:
      "Tactile IoT drumming system that trains timing, technique, and form. Three ESP-32 microcontrollers coordinate: IMU/FSR force sensing on the drumstick, ultrasonic sensor for drum-center alignment, and a brush motor that holds a demonstrating drumstick at precise angles. PID-tuned motor achieves precise angle matching.",
    specs: { MCUs: "3× ESP-32", sensors: "IMU + FSR", tempo: "Custom BPM" },
    details: [
      { heading: "Problem", text: "Learning to drum has a steep practice curve. The system was designed to train timing, striking position, and form while allowing the learner to choose a practice tempo." },
      { heading: "Sensing and feedback", text: "A gyroscope and accelerometer mount to the drumstick in a 3D-printed enclosure. A force-sensitive resistor tracks impact force, while an ultrasonic sensor measures distance from the drum edge to guide center strikes." },
      { heading: "Three-controller architecture", text: "ESP #1 drives the actuator hub, brush motor, speaker, and dual motor encoder. ESP #2 handles the ultrasonic sensor and red/green center-strike LED. ESP #3 reads the force-sensitive sensor and IMU, including timing between impacts." },
      { heading: "Control behavior", text: "The brush motor was calibrated to move the demonstrating drumstick to a new angle every five seconds. ESP-NOW data plots force and grip angle; a discrepancy above 5 N triggers a recommendation with the measured averages." },
    ],
    image: "/drumstick-tutor.png",
    year: "2025",
  },
];

const EXPERIENCE = [
  {
    role: "Lab Systems Test Engineering Intern",
    company: "The Boeing Company",
    location: "Long Beach, CA",
    period: "Summer 2026",
    bullets: [
      "Engineered a C/C++ software GUI application to manage 30+ discrete signals, utilizing shared memory for synchronized read/write buffers and circular queue implementation",
      "Modernized desktop simulation software by building a C/C++ monitoring window for ARINC 429 bus protocol to streamline signal conversion",
      "Executed test procedures on VMEbus chassis by analyzing bus addresses and probing test points to verify card initialization",
    ],
  },
  {
    role: "Product Quality Engineering Intern",
    company: "Wisk Aero — Boeing Subsidiary",
    location: "Mountain View, CA",
    period: "Summer 2025",
    bullets: [
      "Spearheaded an automated dashboard of Non-conformance Reports (NCRs) to categorize 1,200+ manufacturing defects, summarize design changes, and identify proactive measures to improve production flows",
      "Executed a Python NLP pipeline to sort defect reports by key terms, expanding defect coverage by 140%",
      "Led a cross-functional initiative with 15+ engineers to publish standardized firmware logging processes for 10+ components",
    ],
  },
  {
    role: "Embedded Systems Intern",
    company: "CITRIS Banatao Institute — UC Berkeley",
    location: "Berkeley, CA",
    period: "Summer 2024",
    bullets: [
      "Refined PCB designs for manufacturability in KiCAD, integrating IMUs, thermal cameras, and Bluetooth sensors",
      "Trained and designed TensorFlow algorithms for real-time wildfire hazard detection on an IoT-powered drone and power grid safety system",
    ],
  },
  {
    role: "Dynamics Engineer",
    company: "CalSol — UC Berkeley Formula Solar Car",
    location: "Berkeley, CA",
    period: "Jan 2026 – Present",
    bullets: [
      "Coded a MATLAB program to tune pedal ratios, optimizing brake requirements and reducing forward bias",
      "Designed and manufactured a custom caliper mount to reduce stress concentrations and increase safety factors by 200%",
      "Machined and tested 10+ carbon fiber A-arms via destructive Instron tests and epoxy injection",
    ],
  },
];

const SKILLS = [
  { name: "SolidWorks / Siemens NX / Onshape", level: 92, category: "CAD" },
  { name: "ANSYS CFD / SolidWorks FEA", level: 85, category: "Simulation" },
  { name: "Python / MATLAB / C++", level: 88, category: "Coding" },
  { name: "CNC / Mill / Lathe Machining", level: 80, category: "Machining" },
  { name: "FDM / SLA 3D Printing", level: 90, category: "Prototyping" },
  { name: "PCB Design (KiCAD)", level: 75, category: "Electronics" },
  { name: "GD&T / DFM", level: 87, category: "Standards" },
  { name: "LabView / Oscilloscope / FMEA", level: 82, category: "Testing" },
];

function useInView(threshold = 0.15) {
  const ref = useRef<HTMLDivElement>(null);
  const [inView, setInView] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) { setInView(true); obs.disconnect(); }
      },
      { threshold }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, [threshold]);
  return { ref, inView };
}

function SkillBar({ name, level, category }: { name: string; level: number; category: string }) {
  const { ref, inView } = useInView();
  return (
    <div ref={ref} className="group">
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-3">
          <span className="font-mono text-xs" style={{ color: "var(--primary)" }}>{category}</span>
          <span className="text-sm font-medium" style={{ color: "var(--foreground)" }}>{name}</span>
        </div>
        <span className="font-mono text-xs" style={{ color: "var(--muted-foreground)" }}>{level}%</span>
      </div>
      <div className="h-px w-full" style={{ background: "var(--muted)" }}>
        <div
          className="h-px transition-all duration-1000 ease-out"
          style={{
            width: inView ? `${level}%` : "0%",
            background: "linear-gradient(90deg, var(--primary), rgba(91,158,107,0.4))",
          }}
        />
      </div>
    </div>
  );
}

function Reveal({ children, delay = 0, className = "" }: { children: ReactNode; delay?: number; className?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  const [inView, setInView] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) { setInView(true); obs.disconnect(); }
      },
      { threshold: 0.12 }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return (
    <div
      ref={ref}
      className={`reveal ${inView ? "in-view" : ""} ${delay ? `reveal-delay-${delay}` : ""} ${className}`}
    >
      {children}
    </div>
  );
}

function ProjectCard({ project, onClick }: { project: typeof PROJECTS[0]; onClick: () => void }) {
  return (
    <article
      className="project-card flex flex-col"
      onClick={onClick}
      style={{
        background: "var(--card)",
        border: "1px solid var(--border)",
        overflow: "hidden",
        cursor: "pointer",
        borderRadius: "16px",
      }}
    >
      <div className="relative overflow-hidden" style={{ height: 200, background: "#fffbf0" }}>
        <img
          src={project.image}
          alt={project.title}
          className="w-full h-full object-cover soft-overlay"
          style={{ opacity: 0.7, filter: "saturate(1.15) brightness(1.05)" }}
        />
        <div
          className="absolute inset-0"
          style={{ background: "linear-gradient(to top, var(--card) 0%, transparent 50%)" }}
        />
        <div className="absolute top-3 left-3">
          <span
            className="font-mono text-xs px-2 py-1"
            style={{
              background: "rgba(91,158,107,0.15)",
              color: "var(--primary)",
              border: "1px solid rgba(91,158,107,0.3)",
            }}
          >
            {project.category}
          </span>
        </div>
        <div className="absolute top-3 right-3 font-mono text-xs" style={{ color: "var(--muted-foreground)" }}>
          {project.year}
        </div>
        <div
          className="absolute bottom-3 left-3 font-mono text-2xl font-medium"
          style={{ color: "rgba(91,158,107,0.2)" }}
        >
          {project.id}
        </div>
      </div>

      <div className="flex flex-col flex-1 p-5 gap-3">
        <div>
          <h3 className="font-display text-xl font-semibold tracking-wide" style={{ color: "var(--foreground)" }}>
            {project.title}
          </h3>
          <div className="font-mono text-xs mt-1" style={{ color: "var(--muted-foreground)" }}>
            {project.org}
          </div>
        </div>
        <p className="text-sm leading-relaxed" style={{ color: "var(--muted-foreground)" }}>
          {project.description}
        </p>
        <div className="flex flex-wrap gap-2 mt-1">
          {project.tags.map((tag) => (
            <span
              key={tag}
              className="font-mono text-xs px-2 py-0.5"
              style={{
                background: "var(--muted)",
                color: "var(--secondary-foreground)",
                border: "1px solid var(--border)",
              }}
            >
              {tag}
            </span>
          ))}
        </div>
        <div
          className="mt-auto pt-4 grid grid-cols-3 gap-2 border-t"
          style={{ borderColor: "var(--border)" }}
        >
          {Object.entries(project.specs).map(([k, v]) => (
            <div key={k} className="text-center">
              <div className="font-mono text-xs font-medium" style={{ color: "var(--primary)" }}>{v}</div>
              <div className="font-mono text-xs mt-0.5" style={{ color: "var(--muted-foreground)" }}>{k}</div>
            </div>
          ))}
        </div>
      </div>
    </article>
  );
}

export default function App() {
  const [activeSection, setActiveSection] = useState("Home");
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeJob, setActiveJob] = useState(0);
  const [formState, setFormState] = useState({ name: "", email: "", message: "" });
  const [submitted, setSubmitted] = useState(false);
  const [carouselIndex, setCarouselIndex] = useState<number | null>(null);

  const carouselOpen = carouselIndex !== null;

  const openCarousel = (index: number) => setCarouselIndex(index);
  const closeCarousel = () => setCarouselIndex(null);
  const nextProject = () => setCarouselIndex((c) => (c === null ? 0 : (c + 1) % PROJECTS.length));
  const prevProject = () => setCarouselIndex((c) => (c === null ? 0 : (c - 1 + PROJECTS.length) % PROJECTS.length));

  const scrollTo = (id: string) => {
    const el = document.getElementById(id.toLowerCase());
    if (el) el.scrollIntoView({ behavior: "smooth" });
    setMenuOpen(false);
    setActiveSection(id);
  };

  useEffect(() => {
    const handleScroll = () => {
      for (const s of [...NAV_LINKS].reverse()) {
        const el = document.getElementById(s.toLowerCase());
        if (el && window.scrollY >= el.offsetTop - 120) {
          setActiveSection(s);
          break;
        }
      }
    };
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  useEffect(() => {
    if (!carouselOpen) return;
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") closeCarousel();
      if (e.key === "ArrowRight") nextProject();
      if (e.key === "ArrowLeft") prevProject();
    };
    window.addEventListener("keydown", handleKey);
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", handleKey);
      document.body.style.overflow = "";
    };
  }, [carouselOpen]);

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    setSubmitted(true);
  };

  return (
    <div className="min-h-screen" style={{ background: "var(--background)", color: "var(--foreground)" }}>

      {/* NAV */}
      <nav
        className="fixed top-0 left-0 right-0 z-50"
        style={{
          background: "rgba(255, 251, 240, 0.9)",
          backdropFilter: "blur(12px)",
          borderBottom: "1px solid var(--border)",
        }}
      >
        <div className="max-w-7xl mx-auto px-6 flex items-center justify-between h-16">
          <div className="flex items-center gap-3">
            <div
              className="w-8 h-8 flex items-center justify-center font-mono text-xs font-medium"
              style={{ border: "1px solid var(--primary)", color: "var(--primary)" }}
            >
              AW
            </div>
            <div>
              <div className="font-display text-base font-semibold tracking-widest uppercase">
                Allison Wang
              </div>
              <div className="font-mono text-xs" style={{ color: "var(--muted-foreground)" }}>
                Mechanical Engineer · UC Berkeley
              </div>
            </div>
          </div>

          <div className="hidden md:flex items-center gap-8">
            {NAV_LINKS.map((link) => (
              <button
                key={link}
                onClick={() => scrollTo(link)}
                className={`nav-link font-mono text-xs uppercase tracking-widest ${activeSection === link ? "active" : ""}`}
                style={{
                  color: activeSection === link ? "var(--primary)" : "var(--muted-foreground)",
                  background: "none",
                  border: "none",
                  cursor: "pointer",
                  padding: "4px 0",
                }}
              >
                {link}
              </button>
            ))}
            <a
              href="mailto:alwsanjose@gmail.com"
              className="site-button font-mono text-xs uppercase tracking-widest"
              style={{
                background: "var(--primary)",
                color: "var(--primary-foreground)",
                fontWeight: 600,
                textDecoration: "none",
                borderRadius: "8px",
              }}
            >
              About Me
            </a>
          </div>

          <button
            className="md:hidden flex flex-col gap-1.5 p-2"
            onClick={() => setMenuOpen(!menuOpen)}
            aria-label="Toggle menu"
            style={{ background: "none", border: "none", cursor: "pointer" }}
          >
            {[0, 1, 2].map((i) => (
              <span
                key={i}
                className="block h-px w-6 transition-all duration-200"
                style={{
                  background: "var(--foreground)",
                  transform:
                    menuOpen && i === 0
                      ? "rotate(45deg) translate(3px, 3px)"
                      : menuOpen && i === 2
                      ? "rotate(-45deg) translate(3px, -3px)"
                      : menuOpen && i === 1
                      ? "scaleX(0)"
                      : "none",
                }}
              />
            ))}
          </button>
        </div>

        {menuOpen && (
          <div className="md:hidden flex flex-col px-6 pb-4" style={{ borderTop: "1px solid var(--border)" }}>
            {NAV_LINKS.map((link) => (
              <button
                key={link}
                onClick={() => scrollTo(link)}
                className="font-mono text-xs uppercase tracking-widest text-left py-3 w-full"
                style={{
                  color: activeSection === link ? "var(--primary)" : "var(--muted-foreground)",
                  background: "none",
                  border: "none",
                  borderBottom: "1px solid var(--border)",
                  cursor: "pointer",
                }}
              >
                {link}
              </button>
            ))}
          </div>
        )}
      </nav>

      {/* HERO */}
      <section
        id="home"
        className="relative min-h-screen flex items-center ghibli-sky"
        style={{ paddingTop: 64 }}
      >
        {["top-20 left-6", "top-20 right-6", "bottom-12 left-6", "bottom-12 right-6"].map((pos, i) => (
          <div key={i} className={`absolute ${pos} hidden lg:block`} style={{ opacity: 0.4 }}>
            <div
              className="w-6 h-6"
              style={{
                borderTop: i < 2 ? "1px solid var(--primary)" : "none",
                borderBottom: i >= 2 ? "1px solid var(--primary)" : "none",
                borderLeft: i % 2 === 0 ? "1px solid var(--primary)" : "none",
                borderRight: i % 2 === 1 ? "1px solid var(--primary)" : "none",
              }}
            />
          </div>
        ))}

        <div className="max-w-7xl mx-auto px-6 w-full py-24">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div>
              <div className="flex items-center gap-3 mb-6">
                <div className="w-8 h-px" style={{ background: "var(--primary)" }} />
                <span className="font-mono text-xs uppercase tracking-widest" style={{ color: "var(--primary)" }}>
                  Engineering Portfolio · 2026
                </span>
              </div>

              <div>
                <h1 className="font-display font-black leading-none mb-3" style={{ fontSize: "clamp(3rem, 8vw, 5.5rem)" }}>
                  <span className="block" style={{ color: "var(--foreground)" }}>ALLISON</span>
                  <span className="block" style={{ color: "var(--primary)" }}>WANG</span>
                </h1>

                <div className="font-mono text-sm mb-6" style={{ color: "var(--muted-foreground)" }}>
                  B.S. Mechanical Engineering · UC Berkeley · GPA 3.8 · May 2027
                </div>

                <p className="text-base leading-relaxed max-w-md mb-8" style={{ color: "var(--muted-foreground)" }}>
                  I'm a motivated engineer looking to use my <strong style={{ color: "var(--foreground)" }}>mechanical design</strong>, <strong style={{ color: "var(--foreground)" }}>testing</strong>, and <strong style={{ color: "var(--foreground)" }}>coding</strong> skills to tackle tough, impactful problems.
                </p>
              </div>

              <div className="flex flex-wrap gap-4">
                <button
                  onClick={() => scrollTo("Projects")}
                  className="site-button font-mono text-sm uppercase tracking-widest"
                  style={{
                    background: "var(--primary)",
                    color: "var(--primary-foreground)",
                    border: "none",
                    cursor: "pointer",
                    fontWeight: 600,
                    borderRadius: "10px",
                  }}
                >
                  View Projects
                </button>
               <a
                href="/AllisonWang_CV.pdf"
                className="site-button font-mono text-sm uppercase tracking-widest transition-colors"
                style={{
                  background: "transparent",
                  color: "var(--foreground)",
                  border: "1px solid var(--border)",
                  textDecoration: "none",
                  borderRadius: "10px",
                }}
                onMouseEnter={(e) => (e.currentTarget.style.borderColor = "var(--primary)")}
                onMouseLeave={(e) => (e.currentTarget.style.borderColor = "var(--border)")}
              >
                Resume
              </a>

              </div>

              <div className="grid grid-cols-3 gap-4 mt-12 pt-8" style={{ borderTop: "1px solid var(--border)" }}>
                {[
                  { value: "4", label: "Projects" },
                  { value: "3.8", label: "GPA" },
                  { value: "3×", label: "Internships" },
                ].map((s) => (
                  <div key={s.label}>
                    <div className="font-display text-2xl font-bold" style={{ color: "var(--primary)" }}>{s.value}</div>
                    <div className="font-mono text-xs mt-1" style={{ color: "var(--muted-foreground)" }}>{s.label}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Hero image */}
            <div className="relative hidden lg:block">
              <div
                className="relative overflow-hidden"
                style={{ border: "1px solid var(--border)", height: 500, background: "#fffbf0", borderRadius: "16px" }}
              >
                <img
                  src="https://images.unsplash.com/photo-1614728263952-84ea256f9679?w=900&h=600&fit=crop&auto=format"
                  alt="Rocket launch — aerospace engineering inspiration"
                  className="w-full h-full object-cover soft-overlay"
                  style={{ opacity: 0.65, filter: "saturate(1.15) brightness(1.05)" }}
                />
                <div
                  className="absolute inset-0"
                  style={{
                    background:
                      "linear-gradient(135deg, rgba(91,158,107,0.07) 0%, transparent 60%), linear-gradient(to bottom, transparent 60%, var(--background) 100%)",
                  }}
                />
                <div className="absolute bottom-0 left-0 right-0 p-4">
                  <div
                    className="font-mono text-xs p-3"
                    style={{
                      background: "rgba(74, 63, 53, 0.88)",
                      border: "1px solid var(--border)",
                      color: "#fffbf0",
                      borderRadius: "10px",
                    }}
                  >
                    <span style={{ color: "var(--primary)" }}>FIG 1.1</span> — Space Technologies and Rocketry · Yeast Life Support Payload
                  </div>
                </div>
                <div className="absolute top-3 right-3 font-mono text-xs" style={{ color: "rgba(91,158,107,0.4)" }}>
                  UC Berkeley · 2026
                </div>
              </div>
              <div
                className="absolute -bottom-3 -right-3 w-full h-full -z-10"
                style={{ border: "1px solid rgba(91,158,107,0.1)" }}
              />
            </div>
          </div>
        </div>
      </section>

      {/* PROJECTS */}
      <section id="projects" className="full-section" style={{ background: "var(--secondary)" }}>
        <div className="max-w-7xl mx-auto px-6 w-full py-24">
          <Reveal>
            <div className="mb-12">
              <div className="flex items-center gap-3 mb-4">
                <span className="font-mono text-xs uppercase tracking-widest section-rule" style={{ color: "var(--primary)" }}>
                  Selected Work
                </span>
              </div>
              <h2 className="font-heading font-black" style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)", lineHeight: 1 }}>
                ENGINEERING<br />
                <span style={{ color: "var(--primary)" }}>PROJECTS</span>
              </h2>
            </div>
          </Reveal>

          <Reveal delay={2}>
            <div className="grid gap-6 sm:grid-cols-2">
              {PROJECTS.map((project, i) => (
                <ProjectCard key={project.id} project={project} onClick={() => openCarousel(i)} />
              ))}
            </div>
          </Reveal>
        </div>
      </section>

      {/* EXPERIENCE */}
      <section id="experience" className="full-section ghibli-meadow">
        <div className="max-w-7xl mx-auto px-6 w-full py-24">
          <Reveal>
            <div className="mb-12">
              <div className="flex items-center gap-3 mb-4">
                <span className="font-mono text-xs uppercase tracking-widest section-rule" style={{ color: "var(--primary)" }}>
                  Work History
                </span>
              </div>
              <h2 className="font-heading font-black" style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)", lineHeight: 1 }}>
                RELEVANT<br />
                <span style={{ color: "var(--primary)" }}>EXPERIENCE</span>
              </h2>
            </div>
          </Reveal>

          <Reveal delay={2}>
            <div className="grid lg:grid-cols-3 gap-8">
            {/* Tab sidebar */}
            <div className="flex flex-col gap-1">
              {EXPERIENCE.map((job, i) => (
                <button
                  key={i}
                  onClick={() => setActiveJob(i)}
                  className="text-left px-4 py-4 transition-all"
                  style={{
                    background: activeJob === i ? "var(--card)" : "transparent",
                    borderLeft: `2px solid ${activeJob === i ? "var(--primary)" : "var(--border)"}`,
                    border: activeJob === i ? "1px solid var(--border)" : "1px solid transparent",
                    borderLeftWidth: 2,
                    cursor: "pointer",
                    borderRadius: "10px",
                  }}
                >
                  <div className="font-mono text-xs uppercase tracking-widest" style={{ color: activeJob === i ? "var(--primary)" : "var(--muted-foreground)" }}>
                    {job.period}
                  </div>
                  <div className="text-sm font-medium mt-1" style={{ color: activeJob === i ? "var(--foreground)" : "var(--muted-foreground)" }}>
                    {job.company}
                  </div>
                </button>
              ))}
            </div>

            {/* Detail panel */}
            <div
              className="lg:col-span-2 p-6"
              style={{ background: "var(--card)", border: "1px solid var(--border)" }}
            >
              <div className="mb-4">
                <h3 className="font-display text-xl font-semibold" style={{ color: "var(--foreground)" }}>
                  {EXPERIENCE[activeJob].role}
                </h3>
                <div className="flex flex-wrap items-center gap-3 mt-1">
                  <span className="font-mono text-sm" style={{ color: "var(--primary)" }}>
                    {EXPERIENCE[activeJob].company}
                  </span>
                  <span className="font-mono text-xs" style={{ color: "var(--muted-foreground)" }}>
                    {EXPERIENCE[activeJob].location}
                  </span>
                  <span className="font-mono text-xs" style={{ color: "var(--muted-foreground)" }}>
                    {EXPERIENCE[activeJob].period}
                  </span>
                </div>
              </div>
              <div className="flex flex-col gap-3">
                {EXPERIENCE[activeJob].bullets.map((b, i) => (
                  <div key={i} className="flex gap-3 items-start">
                    <div
                      className="w-1.5 h-1.5 flex-shrink-0 mt-1.5"
                      style={{ background: "var(--primary)" }}
                    />
                    <p className="text-sm leading-relaxed" style={{ color: "var(--muted-foreground)" }}>{b}</p>
                  </div>
                ))}
              </div>

              {/* Education note at bottom of Boeing */}
              {activeJob === 0 && (
                <div
                  className="mt-6 pt-5 flex gap-4"
                  style={{ borderTop: "1px solid var(--border)" }}
                >
                  <div>
                    <div className="font-mono text-xs uppercase tracking-widest mb-1" style={{ color: "var(--primary)" }}>
                      Education
                    </div>
                    <div className="text-sm font-medium" style={{ color: "var(--foreground)" }}>
                      University of California, Berkeley
                    </div>
                    <div className="text-sm" style={{ color: "var(--muted-foreground)" }}>
                      B.S. Mechanical Engineering · GPA 3.8 · Fall 2023 – Spring 2027
                    </div>
                  </div>
                </div>
              )}
            </div>
            </div>
          </Reveal>
        </div>
      </section>

      {/* SKILLS */}
      <section id="skills" className="full-section" style={{ background: "var(--secondary)" }}>
        <div className="max-w-7xl mx-auto px-6 w-full py-24">
          <Reveal>
            <div className="grid lg:grid-cols-2 gap-16 items-start">
              <div>
                <div className="flex items-center gap-3 mb-4">
                  <span className="font-mono text-xs uppercase tracking-widest section-rule" style={{ color: "var(--primary)" }}>
                    Capabilities
                  </span>
                </div>
                <h2 className="font-heading font-black mb-6" style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)", lineHeight: 1 }}>
                  TECHNICAL<br />
                  <span style={{ color: "var(--primary)" }}>SKILLS</span>
                </h2>
              <p className="text-sm leading-relaxed mb-8" style={{ color: "var(--muted-foreground)" }}>
                Hands-on proficiency across simulation, mechanical design, rapid prototyping, embedded electronics, and software. Bilingual in English and Chinese.
              </p>

              <div
                className="p-5"
                style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: "14px" }}
              >
                <div className="font-mono text-xs uppercase tracking-widest mb-4" style={{ color: "var(--primary)" }}>
                  Tools & Technologies
                </div>
                {[
                  ["Simulation", "ANSYS CFD, SolidWorks FEA"],
                  ["Prototyping", "Injection molding, CNC, Metal 3D print, Laser cut"],
                  ["Electronics", "KiCAD, Arduino, ESP-32, LabView, Oscilloscope"],
                  ["Software", "Python, MATLAB, Arduino, Java, C++"],
                  ["Standards", "GD&T, Root Cause Analysis, FMEA"],
                ].map(([label, value]) => (
                  <div
                    key={label}
                    className="flex gap-3 py-2.5"
                    style={{ borderBottom: "1px solid var(--border)" }}
                  >
                    <div className="w-1.5 h-1.5 flex-shrink-0 mt-1.5" style={{ background: "var(--primary)" }} />
                    <div>
                      <span className="font-mono text-xs font-medium" style={{ color: "var(--foreground)" }}>{label}: </span>
                      <span className="text-xs" style={{ color: "var(--muted-foreground)" }}>{value}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="flex flex-col gap-6">
              {SKILLS.map((skill) => (
                <SkillBar key={skill.name} {...skill} />
              ))}
            </div>
            </div>
          </Reveal>
        </div>
      </section>

      {/* CONTACT */}
      <section id="contact" className="full-section ghibli-sky">
        <div className="max-w-7xl mx-auto px-6 w-full py-24">
          <Reveal>
            <div className="grid lg:grid-cols-2 gap-16">
              <div>
                <div className="flex items-center gap-3 mb-4">
                  <span className="font-mono text-xs uppercase tracking-widest section-rule" style={{ color: "var(--primary)" }}>
                    Get In Touch
                  </span>
                </div>
                <h2 className="font-heading font-black mb-6" style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)", lineHeight: 1 }}>
                  LET'S<br />
                  <span style={{ color: "var(--primary)" }}>CONNECT</span>
                </h2>
              <p className="text-sm leading-relaxed mb-10" style={{ color: "var(--muted-foreground)" }}>
                Currently seeking internship and full-time opportunities in mechanical engineering, mechatronics, and embedded systems. Open to roles in aerospace, robotics, and product development.
              </p>

              <div className="flex flex-col gap-5">
                {[
                  { label: "Email", value: "alwsanjose@gmail.com", href: "mailto:alwsanjose@gmail.com" },
                  { label: "Academic", value: "alliwang@berkeley.edu", href: "mailto:alliwang@berkeley.edu" },
                  { label: "LinkedIn", value: "linkedin.com/in/alli-wang", href: "https://www.linkedin.com/in/alli-wang/" },
                  { label: "Location", value: "San Jose, CA · Berkeley, CA" },
                  { label: "Phone", value: "(408) 265-8088" },
                ].map((item) => (
                  <div key={item.label} className="flex gap-4 items-start pb-4" style={{ borderBottom: "1px solid var(--border)" }}>
                    <div className="font-mono text-xs pt-0.5 flex-shrink-0" style={{ color: "var(--primary)", minWidth: 80 }}>
                      {item.label}
                    </div>
                    {item.href ? (
                      <a
                        href={item.href}
                        className="text-sm transition-colors"
                        style={{ color: "var(--foreground)", textDecoration: "none" }}
                        onMouseEnter={(e) => (e.currentTarget.style.color = "var(--primary)")}
                        onMouseLeave={(e) => (e.currentTarget.style.color = "var(--foreground)")}
                      >
                        {item.value}
                      </a>
                    ) : (
                      <div className="text-sm" style={{ color: "var(--foreground)" }}>{item.value}</div>
                    )}
                  </div>
                ))}
              </div>
            </div>

            <div>
              {submitted ? (
                <div
                  className="flex flex-col items-center justify-center h-full text-center p-12"
                  style={{ border: "1px solid var(--border)", background: "var(--card)", minHeight: 340 }}
                >
                  <div
                    className="w-12 h-12 flex items-center justify-center mb-4 font-mono text-xl"
                    style={{ border: "1px solid var(--primary)", color: "var(--primary)" }}
                  >
                    ✓
                  </div>
                  <div className="font-display text-2xl font-bold mb-2">Message Sent</div>
                  <p className="text-sm" style={{ color: "var(--muted-foreground)" }}>
                    Thanks for reaching out. I'll get back to you soon!
                  </p>
                </div>
              ) : (
                <form onSubmit={handleSubmit} className="flex flex-col gap-5">
                  {[
                    { id: "name", label: "Name", type: "text", placeholder: "Your name" },
                    { id: "email", label: "Email", type: "email", placeholder: "your@email.com" },
                  ].map((field) => (
                    <div key={field.id} className="flex flex-col gap-1.5">
                      <label className="font-mono text-xs uppercase tracking-widest" style={{ color: "var(--muted-foreground)" }}>
                        {field.label}
                      </label>
                      <input
                        type={field.type}
                        placeholder={field.placeholder}
                        value={formState[field.id as keyof typeof formState]}
                        onChange={(e) => setFormState({ ...formState, [field.id]: e.target.value })}
                        required
                        className="text-sm px-4 py-3 outline-none"
                        style={{
                          background: "var(--card)",
                          border: "1px solid var(--border)",
                          color: "var(--foreground)",
                          fontFamily: "inherit",
                          borderRadius: "10px",
                        }}
                        onFocus={(e) => (e.currentTarget.style.borderColor = "var(--primary)")}
                        onBlur={(e) => (e.currentTarget.style.borderColor = "var(--border)")}
                      />
                    </div>
                  ))}
                  <div className="flex flex-col gap-1.5">
                    <label className="font-mono text-xs uppercase tracking-widest" style={{ color: "var(--muted-foreground)" }}>
                      Message
                    </label>
                    <textarea
                      rows={5}
                      placeholder="Tell me about the opportunity or project..."
                      value={formState.message}
                      onChange={(e) => setFormState({ ...formState, message: e.target.value })}
                      required
                      className="text-sm px-4 py-3 outline-none resize-none"
                      style={{
                        background: "var(--card)",
                        border: "1px solid var(--border)",
                        color: "var(--foreground)",
                        fontFamily: "inherit",
                        borderRadius: "10px",
                      }}
                      onFocus={(e) => (e.currentTarget.style.borderColor = "var(--primary)")}
                      onBlur={(e) => (e.currentTarget.style.borderColor = "var(--border)")}
                    />
                  </div>
                  <button
                    type="submit"
                    className="site-button font-mono text-sm uppercase tracking-widest hover:opacity-90 transition-opacity"
                    style={{
                      background: "var(--primary)",
                      color: "var(--primary-foreground)",
                      border: "none",
                      cursor: "pointer",
                      fontFamily: "inherit",
                      fontWeight: 600,
                      borderRadius: "10px",
                    }}
                  >
                    Send Message →
                  </button>
                </form>
              )}
            </div>
            </div>
          </Reveal>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="py-8" style={{ background: "var(--card)", borderTop: "1px solid var(--border)" }}>
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="font-mono text-xs" style={{ color: "var(--muted-foreground)" }}>
            © 2026 Allison Wang · San Jose, CA
          </div>
          <div className="font-mono text-xs" style={{ color: "var(--muted-foreground)" }}>
            B.S. Mechanical Engineering · UC Berkeley · GPA 3.8
          </div>
          <div className="flex gap-6">
            {[
              { label: "LinkedIn", href: "https://www.linkedin.com/in/alli-wang/" },
              { label: "WordPress", href: "https://alliwang.wordpress.com" },
              { label: "Email", href: "mailto:alwsanjose@gmail.com" },
            ].map((link) => (
              <a
                key={link.label}
                href={link.href}
                className="font-mono text-xs transition-colors"
                style={{ color: "var(--muted-foreground)", textDecoration: "none" }}
                onMouseEnter={(e) => (e.currentTarget.style.color = "var(--primary)")}
                onMouseLeave={(e) => (e.currentTarget.style.color = "var(--muted-foreground)")}
              >
                {link.label}
              </a>
            ))}
          </div>
        </div>
      </footer>

      {/* PROJECT CAROUSEL MODAL */}
      {carouselOpen && carouselIndex !== null && (
        <div
          className="carousel-overlay"
          role="dialog"
          aria-modal="true"
          aria-label="Project details"
          onClick={closeCarousel}
        >
          <div className="carousel-modal" onClick={(e) => e.stopPropagation()}>
            <button className="carousel-close" onClick={closeCarousel} aria-label="Close">×</button>
            <button className="carousel-arrow carousel-arrow-left" onClick={prevProject} aria-label="Previous">←</button>

            <article className="carousel-slide">
              <div className="carousel-image-wrap">
                <img
                  src={PROJECTS[carouselIndex].image}
                  alt={PROJECTS[carouselIndex].title}
                  className="carousel-image"
                  style={{ opacity: 0.8, filter: "saturate(1.15) brightness(1.05)" }}
                />
                <div className="absolute top-3 left-3">
                  <span
                    className="font-mono text-xs px-2 py-1"
                    style={{
                      background: "rgba(91,158,107,0.15)",
                      color: "var(--primary)",
                      border: "1px solid rgba(91,158,107,0.3)",
                    }}
                  >
                    {PROJECTS[carouselIndex].category}
                  </span>
                </div>
                <div className="absolute top-3 right-3 font-mono text-xs" style={{ color: "var(--muted-foreground)" }}>
                  {PROJECTS[carouselIndex].year}
                </div>
              </div>

              <div className="carousel-content">
                <div className="flex items-center gap-3 mb-2">
                  <span className="font-mono text-2xl font-medium" style={{ color: "rgba(91,158,107,0.3)" }}>
                    {PROJECTS[carouselIndex].id}
                  </span>
                  <span className="font-mono text-xs" style={{ color: "var(--muted-foreground)" }}>
                    {PROJECTS[carouselIndex].org}
                  </span>
                </div>
                <h3 className="font-display text-2xl font-semibold mb-3" style={{ color: "var(--foreground)" }}>
                  {PROJECTS[carouselIndex].title}
                </h3>
                <p className="text-sm leading-relaxed mb-4" style={{ color: "var(--muted-foreground)" }}>
                  {PROJECTS[carouselIndex].description}
                </p>

                <div className="flex flex-wrap gap-2 mb-4">
                  {PROJECTS[carouselIndex].tags.map((tag) => (
                    <span
                      key={tag}
                      className="font-mono text-xs px-2 py-0.5"
                      style={{
                        background: "var(--muted)",
                        color: "var(--secondary-foreground)",
                        border: "1px solid var(--border)",
                      }}
                    >
                      {tag}
                    </span>
                  ))}
                </div>

                <div className="grid grid-cols-3 gap-3 pt-4 border-t" style={{ borderColor: "var(--border)" }}>
                  {Object.entries(PROJECTS[carouselIndex].specs).map(([k, v]) => (
                    <div key={k} className="text-center">
                      <div className="font-mono text-xs font-medium" style={{ color: "var(--primary)" }}>{v}</div>
                      <div className="font-mono text-xs mt-0.5" style={{ color: "var(--muted-foreground)" }}>{k}</div>
                    </div>
                  ))}
                </div>

                <div className="project-journal">
                  <div className="project-journal-label">Project journal</div>
                  <div className="project-journal-sections">
                    {PROJECTS[carouselIndex].details.map((detail) => (
                      <section key={detail.heading} className="project-journal-section">
                        <h4>{detail.heading}</h4>
                        <p>{detail.text}</p>
                      </section>
                    ))}
                  </div>
                </div>
              </div>
            </article>

            <button className="carousel-arrow carousel-arrow-right" onClick={nextProject} aria-label="Next">→</button>

            <div className="carousel-dots">
              {PROJECTS.map((project, i) => (
                <button
                  key={project.id}
                  className={`carousel-dot ${i === carouselIndex ? "is-active" : ""}`}
                  onClick={() => setCarouselIndex(i)}
                  aria-label={`Show ${project.title}`}
                />
              ))}
            </div>

            <p className="carousel-counter">
              {carouselIndex + 1} / {PROJECTS.length}
            </p>
          </div>
        </div>
      )}
    </div>
  );
}


